//
//  Pokemon.swift
//  PokeCP
//
//  Created by Liguo Jiao on 16/8/21.
//  Copyright © 2016年 Liguo Jiao. All rights reserved.
//

import Foundation

class Pokemon {
    var name : String
    var low : Float
    var high : Float
    var candy : Int
    var maxIndex : Int
    var type: String
    var nextGeneration : Pokemon?
    var secondNextGeneration : Pokemon?
    var thirdNextGeneration: Pokemon?

    init(name:String, low:Float, high: Float, candy: Int?, maxIndex: Int, type:String, nextGeneration : Pokemon?, secondNextGeneration: Pokemon?, thirdNextGeneration: Pokemon?) {
        self.name = name
        self.low = low
        self.high = high
        self.candy = candy ?? 0
        self.nextGeneration = nextGeneration
        self.type = type
        self.maxIndex = maxIndex
        self.thirdNextGeneration = thirdNextGeneration
        self.secondNextGeneration = secondNextGeneration
    }
}

let pokemons = [

    Pokemon(name: "Abra", low: 1.1, high: 2.2, candy: 25, maxIndex: 600, type: "Psychic",
        nextGeneration: Pokemon(name: "Kadabra", low: 1.1, high: 1.1, candy: 100, maxIndex: 1131, type: "Psychic",
            nextGeneration: Pokemon(name: "Alakazam", low: 1.1, high: 1.1, candy: 0, maxIndex: 1813, type: "Psychic",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Bellsprout", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Weepinbell", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
            nextGeneration: Pokemon(name: "Victreebel", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Bulbasaur", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Ivysaur", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
            nextGeneration: Pokemon(name: "Venusaur", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Caterpie", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Bug",
        nextGeneration: Pokemon(name: "Metapod", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Bug",
            nextGeneration: Pokemon(name: "Butterfree", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Bug",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Charmander", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fire",
        nextGeneration: Pokemon(name: "Charmeleon", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fire",
            nextGeneration: Pokemon(name: "Charizard", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fire",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Charmeleon", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fire",
        nextGeneration: Pokemon(name: "Charizard", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Clefairy", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fairy",
        nextGeneration: Pokemon(name: "Clefable", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fairy",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Cubone", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Ground",
        nextGeneration: Pokemon(name: "Marowak", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Diglett", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Ground",
        nextGeneration: Pokemon(name: "Dugtrio", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Doduo", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Normal-Flying",
        nextGeneration: Pokemon(name: "Dodrio", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Normal-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Dragonair", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Dragon",
        nextGeneration: Pokemon(name: "Dragonite", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Dragon",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Dratini", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Dragon",
        nextGeneration: Pokemon(name: "Dragonair", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Dragon",
            nextGeneration: Pokemon(name: "Dragonite", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Dragon",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Drowzee", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Psychic",
        nextGeneration: Pokemon(name: "Hypno", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Eevee", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Normal",
        nextGeneration: Pokemon(name: "Vaporeon", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: Pokemon(name: "Jolteon", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Electric",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        thirdNextGeneration: Pokemon(name: "Flareon", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil)),
    Pokemon(name: "Ekans", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison",
        nextGeneration: Pokemon(name: "Arbok", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Exeggcute", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Grass · Psychic",
        nextGeneration: Pokemon(name: "Exeggutor", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass · Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Gastly", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Ghost-Poison",
        nextGeneration: Pokemon(name: "Haunter", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Ghost-Poison",
            nextGeneration: Pokemon(name: "Gengar", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Ghost-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Geodude", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Rock-Ground",
        nextGeneration: Pokemon(name: "Graveler", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Rock-Ground",
            nextGeneration: Pokemon(name: "Golem", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Rock-Ground",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Gloom", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Vileplume", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Goldeen", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Seaking", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Graveler", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Rock-Ground",
        nextGeneration: Pokemon(name: "Golem", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Rock-Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Grimer", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison",
        nextGeneration: Pokemon(name: "Muk", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Growlithe", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fire",
        nextGeneration: Pokemon(name: "Arcanine", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Haunter", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Ghost-Poison",
        nextGeneration: Pokemon(name: "Gengar", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Ghost-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Hitmonlee", low: 1.1, high: 2.2, candy: 50,maxIndex: 2000, type: "Fighting",
        nextGeneration: nil,
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Horsea", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Seadra", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: Pokemon(name: "Kingdra", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Dragon",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Ivysaur", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Venusaur", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Jigglypuff", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Normal-Fairy",
        nextGeneration: Pokemon(name: "Wigglytuff", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Normal-Fairy",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Kabuto", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Rock-Water",
        nextGeneration: Pokemon(name: "Kabutops", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Rock-Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Kadabra", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Psychic",
        nextGeneration: Pokemon(name: "Alakazam", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Koffing", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison",
        nextGeneration: Pokemon(name: "Weezing", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Krabby", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Kingler", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Machoke", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fighting",
        nextGeneration: Pokemon(name: "Machamp", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fighting",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Machop", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fighting",
        nextGeneration: Pokemon(name: "Machoke", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fighting",
            nextGeneration: Pokemon(name: "Machoke", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fighting",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Magikarp", low: 1.1, high: 2.2, candy: 400, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Gyarados", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Magnemite", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Electric-Steel",
        nextGeneration: Pokemon(name: "Magneton", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Electric-Steel",
            nextGeneration: Pokemon(name: "Magnezone", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Electric-Steel",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Mankey", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fighting",
        nextGeneration: Pokemon(name: "Primeape", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fighting",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Meowth", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Normal",
        nextGeneration: Pokemon(name: "Persian", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Normal",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Metapod", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Bug",
        nextGeneration: Pokemon(name: "Butterfree", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Bug-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidoran♀", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison",
        nextGeneration: Pokemon(name: "Nidorina", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison",
            nextGeneration: Pokemon(name: "Nidoqueen", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison-Ground",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidoran♂", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison",
        nextGeneration: Pokemon(name: "Nidorino", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison",
            nextGeneration: Pokemon(name: "Nidoking", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidorina", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison",
        nextGeneration: Pokemon(name: "Nidoqueen", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison-Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidorino", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison",
        nextGeneration: Pokemon(name: "Nidoking", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison-Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Oddish", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Gloom", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
            nextGeneration: Pokemon(name: "Vileplume", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Omanyte", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Rock-Water",
        nextGeneration: Pokemon(name: "Omastar", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Rock-Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Paras", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Bug-Grass",
        nextGeneration: Pokemon(name: "Parasect", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Bug-Grass",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Pidgeotto", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Normal-Flying",
        nextGeneration: Pokemon(name: "Pidgeot", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Normal-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Pidgey", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "",
        nextGeneration: Pokemon(name: "Pidgeotto", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "",
            nextGeneration: Pokemon(name: "Pidgeot", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Normal-Flying",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Pikachu", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Electric",
        nextGeneration: Pokemon(name: "Raichu", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Electric",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Poliwag", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Poliwhirl", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: Pokemon(name: "Poliwrath", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Fighting",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Poliwhirl", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Poliwrath", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Fighting",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Ponyta", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fire",
        nextGeneration: Pokemon(name: "Rapidash", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Psyduck", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Golduck", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Rattata", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Normal",
        nextGeneration: Pokemon(name: "Raticate", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Normal",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Rhyhorn", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Ground-Rock",
        nextGeneration: Pokemon(name: "Rhydon", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Ground-Rock",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Sandshrew", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Ground",
        nextGeneration: Pokemon(name: "Sandslash", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Seel", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Dewgong", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Ice",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Shellder", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Cloyster", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Ice",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Slowpoke", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water-Psychic",
        nextGeneration: Pokemon(name: "Slowbro", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Spearow", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Normal-Flying",
        nextGeneration: Pokemon(name: "Fearow", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Normal-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Squirtle", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Wartortle", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: Pokemon(name: "Blastoise", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Staryu", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Starmie", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Tentacool", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water-Poison",
        nextGeneration: Pokemon(name: "Tentacruel", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Venonat", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Bug-Poison",
        nextGeneration: Pokemon(name: "Venomoth", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Bug-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Voltorb", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Electric",
        nextGeneration: Pokemon(name: "Electrode", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Electric",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Vulpix", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Fire",
        nextGeneration: Pokemon(name: "Ninetales", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Wartortle", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Water",
        nextGeneration: Pokemon(name: "Blastoise", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Weedle", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Bug-Poison",
        nextGeneration: Pokemon(name: "Kakuna", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Bug-Poison",
            nextGeneration: Pokemon(name: "Beedrill", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Bug-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Weepinbell", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Victreebel", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Grass-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Zubat", low: 1.1, high: 2.2, candy: 50, maxIndex: 2000, type: "Poison-Flying",
        nextGeneration: Pokemon(name: "Golbat", low: 1.1, high: 1.1, candy: 50, maxIndex: 2000, type: "Poison-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil)
]
