//
//  Pokemon.swift
//  PokeCP
//
//  Created by Liguo Jiao on 16/8/21.
//  Copyright © 2016年 Liguo Jiao. All rights reserved.
//

import Foundation

class Pokemon {
    var name : String
    var low : Float
    var high : Float
    var candy : Int
    var maxIndex : Int
    var type: String
    var nextGeneration : Pokemon?
    var secondNextGeneration : Pokemon?
    var thirdNextGeneration: Pokemon?

    init(name:String, low:Float, avgCP: Float, high: Float, candy: Int?, maxIndex: Int, type:String, nextGeneration : Pokemon?, secondNextGeneration: Pokemon?, thirdNextGeneration: Pokemon?) {
        self.name = name
        self.low = low
        self.high = high
        self.candy = candy ?? 0
        self.nextGeneration = nextGeneration
        self.type = type
        self.maxIndex = maxIndex
        self.thirdNextGeneration = thirdNextGeneration
        self.secondNextGeneration = secondNextGeneration
    }
}
/*
struct EvolutionItem {
    var name: String
    var low: Float
    var height: Float
    var candy: Int
}

struct EvolutionList {
    var evolutionitems: EvolutionItem
    var numGeneration: Int
}

struct PokemonEvolution {
    var id:Int
    var evolutionLists: EvolutionList
    var numEvolution:Int
}

struct PokemonCanGe {
    var id : Int
    var evolution: Int
    var currentGeneration: Int
}

let p = PokemonCanGe(id: 0, evolution: 2, currentGeneration: 1).
*/

let pokemons = [
    Pokemon(name: "Abra", low: 1.36, avgCP: 1.68, high: 2.0, candy: 25, maxIndex: 600, type: "Psychic",
        nextGeneration: Pokemon(name: "Kadabra", low: 1.41, avgCP: 1.53, high: 1.65, candy: 100, maxIndex: 1131, type: "Psychic",
            nextGeneration: Pokemon(name: "Alakazam", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1813, type: "Psychic",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Bellsprout", low: 1.54, avgCP: 1.57, high: 1.6, candy: 25, maxIndex: 1117, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Weepinbell", low: 1.47, avgCP: 1.495, high: 1.52, candy: 100, maxIndex: 1723, type: "Grass-Poison",
            nextGeneration: Pokemon(name: "Victreebel", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2530, type: "Grass-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Bulbasaur", low: 1.53,avgCP: 1.555, high: 1.58, candy: 25, maxIndex: 1071, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Ivysaur", low: 1.2, avgCP: 1.405, high: 1.61, candy: 100, maxIndex: 1632, type: "Grass-Poison",
            nextGeneration: Pokemon(name: "Venusaur", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2580, type: "Grass-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Caterpie", low: 1.04, avgCP: 1.06, high: 1.08, candy: 12, maxIndex: 443, type: "Bug",
        nextGeneration: Pokemon(name: "Metapod", low: 3.52, avgCP: 3.655, high: 3.79, candy: 50, maxIndex: 477, type: "Bug",
            nextGeneration: Pokemon(name: "Butterfree", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1454, type: "Bug", //here
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Charmander", low: 1.64, avgCP: 1.67, high: 1.7, candy: 25, maxIndex: 955, type: "Fire",
        nextGeneration: Pokemon(name: "Charmeleon", low: 1.71, avgCP: 1.72, high: 1.73, candy: 100, maxIndex: 1557, type: "Fire",
            nextGeneration: Pokemon(name: "Charizard", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2602, type: "Fire",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Charmeleon", low: 1.71, avgCP: 1.72, high: 1.73, candy: 10, maxIndex: 1557, type: "Fire",
        nextGeneration: Pokemon(name: "Charizard", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2602, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Clefairy", low: 2.02, avgCP: 2.11, high: 2.2, candy: 50, maxIndex: 1200, type: "Fairy",
        nextGeneration: Pokemon(name: "Clefable", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2397, type: "Fairy",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Cubone", low: 1.65, avgCP: 1.66, high: 1.67, candy: 50, maxIndex: 1006, type: "Ground",
        nextGeneration: Pokemon(name: "Marowak", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1656, type: "Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Diglett", low: 2.68, avgCP: 2.725, high: 2.77, candy: 50, maxIndex: 456, type: "Ground",
        nextGeneration: Pokemon(name: "Dugtrio", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1168, type: "Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Doduo", low: 2.11, avgCP: 2.175, high: 2.24, candy: 50, maxIndex: 855, type: "Normal-Flying",
        nextGeneration: Pokemon(name: "Dodrio", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1836, type: "Normal-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Dragonair", low: 2.03, avgCP: 2.055, high: 2.08, candy: 100, maxIndex: 1747, type: "Dragon",
        nextGeneration: Pokemon(name: "Dragonite", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 3500, type: "Dragon",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Dratini", low: 1.8, avgCP: 1.825, high: 1.85, candy: 25, maxIndex: 983, type: "Dragon",
        nextGeneration: Pokemon(name: "Dragonair", low: 2.03, avgCP: 2.055, high: 2.08, candy: 100, maxIndex: 1747, type: "Dragon",
            nextGeneration: Pokemon(name: "Dragonite", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 3500, type: "Dragon",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Drowzee", low: 2.05, avgCP: 2.08, high: 2.11, candy: 50, maxIndex: 1075, type: "Psychic",
        nextGeneration: Pokemon(name: "Hypno", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2184, type: "Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Eevee", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2000, type: "Normal",
        nextGeneration: Pokemon(name: "Vaporeon", low: 2.62, avgCP: 2.645, high: 2.67, candy: 50, maxIndex: 2816, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: Pokemon(name: "Jolteon", low: 2.01, avgCP: 2.05, high: 2.09, candy: 50, maxIndex: 2140, type: "Electric",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        thirdNextGeneration: Pokemon(name: "Flareon", low: 2.46, avgCP: 2.55, high: 2.64, candy: 50, maxIndex: 2643, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil)),
    Pokemon(name: "Ekans", low: 2.2, avgCP: 2.265, high: 2.33, candy: 50, maxIndex: 824, type: "Poison",
        nextGeneration: Pokemon(name: "Arbok", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1767, type: "Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Exeggcute", low: 2.7, avgCP: 2.94, high: 3.18, candy: 50, maxIndex: 1099, type: "Grass · Psychic",
        nextGeneration: Pokemon(name: "Exeggutor", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2955, type: "Grass · Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Gastly", low: 1.75, avgCP: 1.79, high: 1.83, candy: 25, maxIndex: 804, type: "Ghost-Poison",
        nextGeneration: Pokemon(name: "Haunter", low: 1.53, avgCP: 1.665, high: 1.8, candy: 100, maxIndex: 1380, type: "Ghost-Poison",
            nextGeneration: Pokemon(name: "Gengar", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2078, type: "Ghost-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Geodude", low: 1.71, avgCP: 1.735, high: 1.76, candy: 25, maxIndex: 849, type: "Rock-Ground",
        nextGeneration: Pokemon(name: "Graveler", low: 1.63, avgCP: 1.675, high: 1.72, candy: 100, maxIndex: 1433, type: "Rock-Ground",
            nextGeneration: Pokemon(name: "Golem", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2303, type: "Rock-Ground",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Gloom", low: 1.48, avgCP: 1.505, high: 1.53, candy: 100, maxIndex: 1689, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Vileplume", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2492, type: "Grass-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Goldeen", low: 2.14, avgCP: 2.19, high: 2.24, candy: 50, maxIndex: 965, type: "Water",
        nextGeneration: Pokemon(name: "Seaking", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2043, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Graveler", low: 1.63, avgCP: 1.675, high: 1.72, candy: 100, maxIndex: 1433, type: "Rock-Ground",
        nextGeneration: Pokemon(name: "Golem", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2303, type: "Rock-Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Grimer", low: 2.03, avgCP: 2.1, high: 2.17, candy: 50, maxIndex: 1284, type: "Poison",
        nextGeneration: Pokemon(name: "Muk", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2602, type: "Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Growlithe", low: 2.25, avgCP: 2.305, high: 2.36, candy: 50, maxIndex: 1335, type: "Fire",
        nextGeneration: Pokemon(name: "Arcanine", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2983, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Haunter", low: 1.53, avgCP: 1.665, high: 1.8, candy: 100, maxIndex: 1380, type: "Ghost-Poison",
        nextGeneration: Pokemon(name: "Gengar", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2078, type: "Ghost-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Hitmonlee", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil,maxIndex: 1492, type: "Fighting",
        nextGeneration: nil,
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Horsea", low: 2.19, avgCP: 2.21, high: 2.23, candy: 50, maxIndex: 794, type: "Water",
        nextGeneration: Pokemon(name: "Seadra", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1713, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Ivysaur", low: 1.2, avgCP: 1.405, high: 1.61, candy: 100, maxIndex: 1632, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Venusaur", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2580, type: "Grass-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Jigglypuff", low: 2.41, avgCP: 2.44, high: 2.47, candy: 50, maxIndex: 917, type: "Normal-Fairy",
        nextGeneration: Pokemon(name: "Wigglytuff", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2177, type: "Normal-Fairy",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Kabuto", low: 1.97, avgCP: 2.17, high: 2.37, candy: 50, maxIndex: 1104, type: "Rock-Water",
        nextGeneration: Pokemon(name: "Kabutops", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2130, type: "Rock-Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Kadabra", low: 1.41, avgCP: 1.53, high: 1.65, candy: 100, maxIndex: 1131, type: "Psychic",
        nextGeneration: Pokemon(name: "Alakazam", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1813, type: "Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Kakuna", low: 3.3, avgCP: 3.36, high: 3.42, candy: 50, maxIndex: 485, type: "Bug-Poison",
        nextGeneration: Pokemon(name: "Beedrill", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1439, type: "Bug-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Koffing", low: 1.95, avgCP: 2.025, high: 2.1, candy: 50, maxIndex: 1151, type: "Poison",
        nextGeneration: Pokemon(name: "Weezing", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2250, type: "Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Krabby", low: 2.35, avgCP: 2.375, high: 2.4, candy: 50, maxIndex: 792, type: "Water",
        nextGeneration: Pokemon(name: "Kingler", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1823, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Machoke", low: 1.48, avgCP: 1.59, high: 1.7, candy: 100, maxIndex: 1760, type: "Fighting",
        nextGeneration: Pokemon(name: "Machamp", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2594, type: "Fighting",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Machop", low: 1.62, avgCP: 1.645, high: 1.67, candy: 25, maxIndex: 1089, type: "Fighting",
        nextGeneration: Pokemon(name: "Machoke", low: 1.48, avgCP: 1.59, high: 1.7, candy: 100, maxIndex: 1760, type: "Fighting",
            nextGeneration: Pokemon(name: "Machamp", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2594, type: "Fighting",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Magikarp", low: 10.1, avgCP: 11.03, high: 11.96, candy: 400, maxIndex: 262, type: "Water",
        nextGeneration: Pokemon(name: "Gyarados", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2688, type: "Water-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Magnemite", low: 2.16, avgCP: 2.18, high: 2.2, candy: 50, maxIndex: 890, type: "Electric-Steel",
        nextGeneration: Pokemon(name: "Magneton", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1879, type: "Electric-Steel",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Mankey", low: 2.15, avgCP: 2.215, high: 2.28, candy: 50, maxIndex: 878, type: "Fighting",
        nextGeneration: Pokemon(name: "Primeape", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1864, type: "Fighting",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Meowth", low: 1.98, avgCP: 2.11, high: 2.24, candy: 50, maxIndex: 756, type: "Normal",
        nextGeneration: Pokemon(name: "Persian", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1631, type: "Normal",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Metapod", low: 3.52, avgCP: 3.655, high: 3.79, candy: 50, maxIndex: 477, type: "Bug",
        nextGeneration: Pokemon(name: "Butterfree", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1454, type: "Bug-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidoran♀", low: 1.62, avgCP: 1.64, high: 1.66, candy: 25, maxIndex: 843, type: "Poison",
        nextGeneration: Pokemon(name: "Nidorina", low: 1.8, avgCP: 1.92, high: 2.04, candy: 100, maxIndex: 1404, type: "Poison",
            nextGeneration: Pokemon(name: "Nidoqueen", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2485, type: "Poison-Ground",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidoran♂", low: 1.65, avgCP: 1.675, high: 1.7, candy: 50, maxIndex: 876, type: "Poison",
        nextGeneration: Pokemon(name: "Nidorino", low: 1.64, avgCP: 1.75, high: 1.86, candy: 100, maxIndex: 1372, type: "Poison",
            nextGeneration: Pokemon(name: "Nidoking", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2475, type: "Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidorina", low: 1.8, avgCP: 1.92, high: 2.04, candy: 100, maxIndex: 1404, type: "Poison",
        nextGeneration: Pokemon(name: "Nidoqueen", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2485, type: "Poison-Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Nidorino", low: 1.64, avgCP: 1.75, high: 1.86, candy: 100, maxIndex: 1372, type: "Poison",
        nextGeneration: Pokemon(name: "Nidoking", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2475, type: "Poison-Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Oddish", low: 1.48, avgCP: 1.495, high: 1.51, candy: 25, maxIndex: 1148, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Gloom", low: 1.48, avgCP: 1.505, high: 1.53, candy: 100, maxIndex: 1689, type: "Grass-Poison",
            nextGeneration: Pokemon(name: "Vileplume", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2492, type: "Grass-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Omanyte", low: 1.99, avgCP: 2.055, high: 2.12, candy: 50, maxIndex: 1119, type: "Rock-Water",
        nextGeneration: Pokemon(name: "Omastar", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2233, type: "Rock-Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Paras", low: 1.92, avgCP: 1.97, high: 2.02, candy: 50, maxIndex: 916, type: "Bug-Grass",
        nextGeneration: Pokemon(name: "Parasect", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1747, type: "Bug-Grass",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Pidgeotto", low: 1.73, avgCP: 1.755, high: 1.78, candy: 50, maxIndex: 1223, type: "Normal-Flying",
        nextGeneration: Pokemon(name: "Pidgeot", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2091, type: "Normal-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Pidgey", low: 1.82, avgCP: 1.885, high: 1.95, candy: 12, maxIndex: 679, type: "",
        nextGeneration: Pokemon(name: "Pidgeotto", low: 1.73, avgCP: 1.755, high: 1.78, candy: 50, maxIndex: 1223, type: "",
            nextGeneration: Pokemon(name: "Pidgeot", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2091, type: "Normal-Flying",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Pikachu", low: 2.33, avgCP: 2.355, high: 2.38, candy: 50, maxIndex: 887, type: "Electric",
        nextGeneration: Pokemon(name: "Raichu", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2028, type: "Electric",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Poliwag", low: 1.72, avgCP: 1.805, high: 1.89, candy: 25, maxIndex: 795, type: "Water",
        nextGeneration: Pokemon(name: "Poliwhirl", low: 1.9, avgCP: 1.93, high: 1.96, candy: 100, maxIndex: 1340, type: "Water",
            nextGeneration: Pokemon(name: "Poliwrath", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2505, type: "Water-Fighting",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Poliwhirl", low: 1.9, avgCP: 1.93, high: 1.96, candy: 100, maxIndex: 1340, type: "Water",
        nextGeneration: Pokemon(name: "Poliwrath", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2505, type: "Water-Fighting",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Ponyta", low: 1.47, avgCP: 1.535, high: 1.6, candy: 50, maxIndex: 1516, type: "Fire",
        nextGeneration: Pokemon(name: "Rapidash", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2199, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Psyduck", low: 2.22, avgCP: 2.255, high: 2.29, candy: 50, maxIndex: 1109, type: "Water",
        nextGeneration: Pokemon(name: "Golduck", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2386, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Rattata", low: 2.61, avgCP: 2.67, high: 2.73, candy: 25, maxIndex: 581, type: "Normal",
        nextGeneration: Pokemon(name: "Raticate", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1444, type: "Normal",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Rhyhorn", low: 1.9, avgCP: 1.905, high: 1.91, candy: 50, maxIndex: 1182, type: "Ground-Rock",
        nextGeneration: Pokemon(name: "Rhydon", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2243, type: "Ground-Rock",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Sandshrew", low: 2.35, avgCP: 2.555, high: 2.76, candy: 50, maxIndex: 798, type: "Ground",
        nextGeneration: Pokemon(name: "Sandslash", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1810, type: "Ground",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Seel", low: 1.96, avgCP: 1.955, high: 2.03, candy: 50, maxIndex: 1107, type: "Water",
        nextGeneration: Pokemon(name: "Dewgong", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2145, type: "Water-Ice",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Shellder", low: 2.62, avgCP: 2.635, high: 2.65, candy: 50, maxIndex: 822, type: "Water",
        nextGeneration: Pokemon(name: "Cloyster", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2052, type: "Water-Ice",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Slowpoke", low: 2.19, avgCP: 2.21, high: 2.21, candy: 50, maxIndex: 1218, type: "Water-Psychic",
        nextGeneration: Pokemon(name: "Slowbro", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2597, type: "Water-Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Spearow", low: 2.58, avgCP: 2.695, high: 2.81, candy: 50, maxIndex: 686, type: "Normal-Flying",
        nextGeneration: Pokemon(name: "Fearow", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1746, type: "Normal-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Squirtle", low: 1.63, avgCP: 1.645, high: 1.66, candy: 25, maxIndex: 1008, type: "Water",
        nextGeneration: Pokemon(name: "Wartortle", low: 1.4, avgCP: 1.525, high: 1.65, candy: 100, maxIndex: 1582, type: "Water",
            nextGeneration: Pokemon(name: "Blastoise", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2542, type: "Water",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Staryu", low: 2.35, avgCP: 2.395, high: 2.44, candy: 50, maxIndex: 937, type: "Water",
        nextGeneration: Pokemon(name: "Starmie", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2182, type: "Water-Psychic",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Tentacool", low: 2.47, avgCP: 2.535, high: 2.6, candy: 50, maxIndex: 905, type: "Water-Poison",
        nextGeneration: Pokemon(name: "Tentacruel", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2220, type: "Water-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Venonat", low: 1.85, avgCP: 1.875, high: 1.9, candy: 50, maxIndex: 1029, type: "Bug-Poison",
        nextGeneration: Pokemon(name: "Venomoth", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1890, type: "Bug-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Voltorb", low: 2.01, avgCP: 2.02, high: 2.03, candy: 50, maxIndex: 839, type: "Electric",
        nextGeneration: Pokemon(name: "Electrode", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1646, type: "Electric",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Vulpix", low: 2.68, avgCP: 2.71, high: 2.74, candy: 50, maxIndex: 2000, type: "Fire",
        nextGeneration: Pokemon(name: "Ninetales", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2000, type: "Fire",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Wartortle", low: 1.4, avgCP: 1.525, high: 1.65, candy: 100, maxIndex: 831, type: "Water",
        nextGeneration: Pokemon(name: "Blastoise", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2188, type: "Water",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Weedle", low: 1.06, avgCP: 1.08, high: 1.1, candy: 12, maxIndex: 449, type: "Bug-Poison",
        nextGeneration: Pokemon(name: "Kakuna", low: 3.3, avgCP: 3.36, high: 3.42, candy: 50, maxIndex: 485, type: "Bug-Poison",
            nextGeneration: Pokemon(name: "Beedrill", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1439, type: "Bug-Poison",
                nextGeneration: nil,
                secondNextGeneration: nil,
                thirdNextGeneration: nil),
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Weepinbell", low: 1.47, avgCP: 1.495, high: 1.52, candy: 100, maxIndex: 1582, type: "Grass-Poison",
        nextGeneration: Pokemon(name: "Victreebel", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 2542, type: "Grass-Poison",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil),
    Pokemon(name: "Zubat", low: 2.9, avgCP: 3.115, high: 3.33, candy: 50, maxIndex: 642, type: "Poison-Flying",
        nextGeneration: Pokemon(name: "Golbat", low: 0.0, avgCP: 0.0, high: 0.0, candy: nil, maxIndex: 1921, type: "Poison-Flying",
            nextGeneration: nil,
            secondNextGeneration: nil,
            thirdNextGeneration: nil),
        secondNextGeneration: nil,
        thirdNextGeneration: nil)
]
